name: NPM Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Restore
      run: npm ci
    -
      name: Build
      run: npm run build