name: NPM Release

on:
  push:
    tags: [ "v*" ]
  pull_request:
    tags: [ "v*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
    -
      name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Release Note
          We regularly update VideoHotkeys to resolve compatibility issues with supported video websites.
          This prebuilt extension is provided for those who cannot access [Chrome Extension Store](https://chrome.google.com/webstore/detail/nhddoifhjbelkmbddllomdnblibdanfe), [Microsoft Edge Add-ons Store](https://microsoftedge.microsoft.com/addons/detail/pamlkecflcalfeaodohfedfndiealmhm), or [Firefox Add-ons Store](https://addons.mozilla.org/firefox/addon/video-hotkeys/).
          To manually install this extension, download and unpack the zip file to a safe place. Then load unpacked extension in the extensions page of your browser.

          To build from source code, one can do:
          ```
          # Restore npm packages
          npm ci

          # Build the TypeScript project with WebPack
          npm run build

          # Zip the dist folder to extension.zip
          npm run zip
          ```
        draft: false
        prerelease: false
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Restore
      run: npm ci
    -
      name: Build
      run: npm run build
    -
      name: Zip
      run: npm run zip
    -
      name: Upload Asset to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./extension.zip"
        asset_name: video-hotkeys.zip
        asset_content_type: application/zip
    -
      name: Archive Extension v3
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: ./extension.zip
    -
      name: Archive Extension v2
      uses: actions/upload-artifact@v3
      with:
        name: extension-v2
        path: ./extension-v2.zip

  publish_edge:
    needs: release
    runs-on: ubuntu-latest
    steps:
    -
      name: Download extension v3
      uses: actions/download-artifact@v3
      with:
        name: extension
    -
      name: Publish to Edge Store
      uses: wdzeng/edge-addon@v1
      with:
        product-id: "a2c50d47-01e9-45d0-8bc1-712d766a7a1b"
        zip-path: "./extension.zip"
        client-id: ${{ secrets.EDGE_CLIENT_ID }}
        client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
        access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

  publish_chrome:
    needs: release
    runs-on: ubuntu-latest
    steps:
    -
      name: Download extension v3
      uses: actions/download-artifact@v3
      with:
        name: extension
    -
      name: Publish to Chrome Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: "publish"
        extension_id: nhddoifhjbelkmbddllomdnblibdanfe
        zip_file: "./extension.zip"
        client_id: ${{ secrets.CHROME_CLIENT_ID }}
        client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}

  publish_firefox:
    needs: release
    runs-on: ubuntu-latest
    steps:
    -
      name: Download extension
      uses: actions/download-artifact@v3
      with:
        name: extension-v2
    -
      name: Publish to Firefox Store
      uses: wdzeng/firefox-addon@v1
      with:
        addon-guid: "{534dc4cb-f239-4b5f-94c1-9c4d80900592}"
        xpi-path: "./extension-v2.zip"
        self-hosted: false
        jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
        jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}